---
- name: Update apt-get system
  apt: >
    upgrade=yes
    update_cache=yes
  become: true

- name: Install development and required packages
  apt: >
    name={{ item }}
    state=present
  with_items:
    - build-essential
    - python-dev
    - python-pip
  become: true


